### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [Tyron18/TMapViews#3]
Hi @Tyron18 , I contribute to open source software by designing logo. I can design a logo for this project if you want. Actually, I got a good idea. I can share with you if you want to see. Have a nice day!

**Comment by Tyron18** [comment]
Hi @reallinfo , I'm keen to have a look at what you have in mind, thank you.

**Comment by reallinfo** [comment]
sure, 
![TM](https://user-images.githubusercontent.com/36298335/54190422-dc312d80-44c4-11e9-9cf0-bd2165f528dc.jpg)

**Comment by Tyron18** [comment]
Looks good, especially like the red. You can make a pull request with the files and let me know what you need from me re. acknowledgments etc.

**Comment by reallinfo** [comment]
Thanks... You can contact me when you need another logo. Best regards.

**Comment by Tyron18** [comment]
Thanks, appreciate it.
